name: Release
on:
  push:
    branches:
      - 'main'
  schedule:
    # Run every day at 8am UTC
    - cron: '0 8 * * *'

jobs:
  example-automation-test:
    # runs-on: medium
    runs-on: ubuntu-latest  # in this case use shared runners, change to self-hosted for non-example
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: simulate test
        id: simulate-test
        run: |
          timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
          ./simulate_test.sh $timestamp
          echo "tag=$timestamp" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        with:
          # get tag from output of simulate test script
          tag: ${{ steps.simulate-test.outputs.tag }}
          artifacts: "output/*"
          bodyFile: "output_body.md"
